const CONTACT={phoneDisplay:"",phoneTel:"",whatsapp:"",email:""};
const qs=(s,c=document)=>c.querySelector(s);const qsa=(s,c=document)=>[...c.querySelectorAll(s)];
document.addEventListener("DOMContentLoaded",()=>{setupNav();setupFAQ();setupReveal();setupContact();setupForm();const y=qs("#year");if(y)y.textContent=new Date().getFullYear()});
function setupNav(){const t=qs(".nav-toggle"),n=qs("#main-nav");if(!t||!n)return;const close=()=>{t.setAttribute("aria-expanded","false");n.classList.remove("open")};t.addEventListener("click",()=>{const o=t.getAttribute("aria-expanded")==="true";t.setAttribute("aria-expanded",String(!o));n.classList.toggle("open",!o)});qsa("a",n).forEach(a=>a.addEventListener("click",close));document.addEventListener("keydown",e=>{if(e.key==="Escape")close()})}
function setupFAQ(){qsa(".faq-item").forEach(i=>{const b=qs(".faq-question",i);b?.addEventListener("click",()=>{const o=b.getAttribute("aria-expanded")==="true";qsa(".faq-item").forEach(x=>{x.classList.remove("open");qs(".faq-question",x)?.setAttribute("aria-expanded","false")});if(!o){i.classList.add("open");b.setAttribute("aria-expanded","true")}})})}
function setupReveal(){const els=qsa(".reveal");if(!("IntersectionObserver" in window)||matchMedia("(prefers-reduced-motion: reduce)").matches){els.forEach(e=>e.classList.add("visible"));return}const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("visible");io.unobserve(e.target)}}),{threshold:.12});els.forEach(e=>io.observe(e))}
function setupContact(){const pl=qs("[data-phone-label]"),el=qs("[data-email-label]");if(CONTACT.phoneDisplay&&pl)pl.textContent=CONTACT.phoneDisplay;if(CONTACT.email&&el)el.textContent=CONTACT.email;qsa(".js-phone").forEach(a=>{a.href=CONTACT.phoneTel?`tel:${CONTACT.phoneTel}`:"#contacto"});qsa(".js-email").forEach(a=>{a.href=CONTACT.email?`mailto:${CONTACT.email}`:"#contacto"});qsa(".js-whatsapp").forEach(a=>{if(CONTACT.whatsapp){a.href=`https://wa.me/${CONTACT.whatsapp}?text=${encodeURIComponent("Hola K-Volt. Quiero realizar una consulta.")}`;a.target="_blank";a.rel="noopener noreferrer"}else a.href="#contacto"})}
function setupForm(){const f=qs("#contact-form");if(!f)return;f.addEventListener("submit",e=>{e.preventDefault();qsa(".field-error",f).forEach(x=>x.textContent="");const d=new FormData(f),nombre=String(d.get("nombre")||"").trim(),tel=String(d.get("telefono")||"").trim(),zona=String(d.get("zona")||"").trim(),msg=String(d.get("mensaje")||"").trim(),cliente=String(d.get("cliente")||"Hogar"),serv=String(d.get("servicio")||"");let ok=true;if(nombre.length<2){err("#nombre","Ingresá tu nombre.");ok=false}if(tel.replace(/\D/g,"").length<7){err("#telefono","Ingresá un teléfono válido.");ok=false}if(zona.length<2){err("#zona","Indicá tu zona.");ok=false}if(msg.length<10){err("#mensaje","Contanos un poco más.");ok=false}if(!ok)return;const text=["Hola K-Volt, quiero realizar una consulta.","",`Tipo: ${cliente}`,`Nombre: ${nombre}`,`Teléfono: ${tel}`,`Zona: ${zona}`,`Servicio: ${serv}`,`Detalle: ${msg}`].join("\n");const fb=qs("#form-feedback");if(!CONTACT.whatsapp){if(fb)fb.textContent="Formulario listo. Falta cargar el WhatsApp real en script.js.";return}window.open(`https://wa.me/${CONTACT.whatsapp}?text=${encodeURIComponent(text)}`,"_blank","noopener,noreferrer");if(fb)fb.textContent="Consulta preparada para WhatsApp."})}
function err(sel,msg){const i=qs(sel),f=i?.closest(".field"),e=f?.querySelector(".field-error");if(e)e.textContent=msg}
